---
- name: Wait for connection
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 120

- name: Install nginx
  ansible.builtin.package:
    name: nginx={{ nginx_version }}
    state: present
  notify: Restart nginx

- name: Setup nginx if web app
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when: aws_ec2_env is defined and aws_ec2_env == "web"
  notify: Restart nginx
